services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    volumes:
      - /root/alist/data:/opt/alist/data
    ports:
      - "8244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
