services:
  ani-rss:
    image: wushuo894/ani-rss:latest
    container_name: ani-rss
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - PORT=7789
      - CONFIG=/config
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./Media:/Media
    ports:
      - 7789:7789

  qBittorrent:
    image: nevinee/qbittorrent
    container_name: qbittorrent-mikan
    hostname: qbittorrent
    restart: always
    tty: true
    stop_grace_period: 10m
    env_file:
      - .env
    volumes:
      - ./qbit-config:/config
      - ./downloads:/downloads
      - ./Media:/Media
    ports:
      - 15768:15768
      - 34567:34567
      - 34567:34567/udp
