services:
  AutoBangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: AutoBangumi
    restart: unless-stopped
    volumes:
      - /root/AutoBangumi/config:/app/config
      - /root/AutoBangumi/data:/app/data
    ports:
      - "8892:7892"
    dns:
      - 223.5.5.5
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - UMASK=022
