version: "3.8"
services:
  qbittorrentee:
    image: superng6/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - WEB_USER=admin
      - WEB_PASSWORD=9xtid6gSECTKqq
      - WEBUIPORT=8080
    volumes:
      - /root/qbittorrent/config:/config
      - /root/download/bangumi:/downloads
    ports:
      - 8001:6881
      - 8001:6881/udp
      - 8080:8080
    restart: unless-stopped
