services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    volumes:
      - /root/uptime-kuma/uptime-kuma-data:/app/data
    ports:
      - 8002:3001
