services:
  alist:
    restart: always
    image: openlistteam/openlist:latest
    container_name: openlist
    user: '0:0'
    volumes:
      - './data:/opt/openlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai
